let books = [
  {
    titre: "The Silent Patient",
    annee_edition: 2019,
    lien_image: "https://covers.openlibrary.org/b/isbn/9781250301703-L.jpg",
    lien_pdf: null,
    resume:
      "A psychological thriller about a woman who shoots her husband and then stops speaking",
    editeur: "Celadon Books",
    nombre_de_page: 336,
    category_id: 4,
    writer_id: 2,
    epub: null,
  },
  {
    titre: "Project Hail Mary",
    annee_edition: 2021,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    lien_pdf: null,
    resume:
      "An astronaut wakes up alone on a spaceship with no memory of his mission",
    editeur: "Ballantine Books",
    nombre_de_page: 496,
    category_id: 2,
    writer_id: 3,
    epub: null,
  },
  {
    titre: "Atomic Habits",
    annee_edition: 2018,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    lien_pdf: null,
    resume: "A guide to building good habits and breaking bad ones",
    editeur: "Avery",
    nombre_de_page: 320,
    category_id: 19,
    writer_id: 4,
    epub: null,
  },
  {
    titre: "The Midnight Library",
    annee_edition: 2020,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    lien_pdf: null,
    resume:
      "A library between life and death where each book represents a different life path",
    editeur: "Viking",
    nombre_de_page: 304,
    category_id: 2,
    writer_id: 5,
    epub: null,
  },
  {
    titre: "Sapiens: A Brief History of Humankind",
    annee_edition: 2011,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    lien_pdf: null,
    resume:
      "Explores the history of Homo sapiens from evolution to modern society",
    editeur: "Harper",
    nombre_de_page: 512,
    category_id: 12,
    writer_id: 1,
    epub: null,
  },
  {
    titre: "Oliver Twist",
    annee_edition: 1838,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780141439747-L.jpg",
    lien_pdf: null,
    resume:
      "The story of an orphan boy who faces many hardships in Victorian London",
    editeur: "Penguin Classics",
    nombre_de_page: 480,
    category_id: 1,
    writer_id: 6,
    epub: "books/Dickens, Charles - Oliver Twist.epub",
  },
  {
    titre: "Les trois mousquetaires",
    annee_edition: 1844,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780140440259-L.jpg",
    lien_pdf: null,
    resume:
      "The adventures of d'Artagnan and the three musketeers in 17th century France",
    editeur: "Penguin Classics",
    nombre_de_page: 704,
    category_id: 1,
    writer_id: 7,
    epub: "books/Dumas, Alexandre - Les trois mousquetaires.epub",
  },
  {
    titre: "Le tour du monde en quatre-vingts jours",
    annee_edition: 1872,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780140449061-L.jpg",
    lien_pdf: null,
    resume:
      "The story of Phileas Fogg's attempt to circumnavigate the world in 80 days",
    editeur: "Penguin Classics",
    nombre_de_page: 256,
    category_id: 8,
    writer_id: 8,
    epub: "books/Verne, Jules - Le tour du monde en quatre-vingts jours.epub",
  },
  {
    titre: "Fables",
    annee_edition: 1668,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780140447210-L.jpg",
    lien_pdf: null,
    resume: "A collection of moral tales featuring animals as characters",
    editeur: "Penguin Classics",
    nombre_de_page: 352,
    category_id: 29,
    writer_id: 9,
    epub: "books/La Fontaine, Jean de - Fables.epub",
  },
  {
    titre: "Sherlock Holmes",
    annee_edition: 1887,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780140439079-L.jpg",
    lien_pdf: null,
    resume:
      "The adventures of the famous detective Sherlock Holmes and his friend Dr. Watson",
    editeur: "Penguin Classics",
    nombre_de_page: 448,
    category_id: 4,
    writer_id: 10,
    epub: "books/Doyle, Artur Conan - Sherlock Holmes.epub",
  },
  {
    titre: "A Christmas Carol",
    annee_edition: 1843,
    lien_image: "https://covers.openlibrary.org/b/isbn/9780140439055-L.jpg",
    lien_pdf: null,
    resume: "A Christmas ghost story about Ebenezer Scrooge's transformation",
    editeur: "Penguin Classics",
    nombre_de_page: 160,
    category_id: 1,
    writer_id: 6,
    epub: "books/Dickens, Charles - A Christmas Carol.epub",
  },
];

export { books };
